// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Histamine_v
{
	public partial class CustomDialogController : NSView
	{
		public CustomDialogController (IntPtr handle) : base (handle)
		{
		}
	}
}
